version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: frontend.dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    ports:
      - "8000:8000"
    networks:
      - app-network
    restart: unless-stopped
    volumes:
      - ./backend:/app

networks:
  app-network:
    driver: bridge